# Generated by Django 3.1.1 on 2020-10-19 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='listings',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
