# Generated by Django 3.1.1 on 2020-10-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201019_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('fashion', 'Fashion'), ('sporting_goods', 'Sporting Goods'), ('electronics', 'Electronics'), ('jewellery_and_watches', 'Jewellery & Watches'), ('motors', 'Motors'), ('toys_and_games', 'Toys & Games'), ('collectables_and_antiques', 'Collectables & Antiques'), ('home_and_garden', 'Home & Garden'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
