# Generated by Django 3.1.1 on 2020-10-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listings_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
