# Generated by Django 3.1.1 on 2020-10-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201026_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='listings',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='listings',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
