# Generated by Django 3.1.1 on 2020-10-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201026_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
