# Generated by Django 3.1.1 on 2020-11-04 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='lisitng_id',
            new_name='listing_id',
        ),
    ]
